### ISSUE TITLE
CIF file available?

### ISSUE THREAD

**Issue by ghost** [kdmsit/crysmmnet#2]
Hi, thank you for sharing your great work.
I downloaded the dataset, but could not find the CIF files.
I would be very grateful if you could give any help.

Sincerely.

**Comment by ghost** [comment]
I found CIF files for MP, but could not for Jarvis.
Thank you:)

**Comment by kdmsit** [comment]
Sorry for very late response !!

I have updated the link in figshare. Please check.
Jarvis - for JARVIS dataset
mp_2018 - for MP dataset
mp_2018_small - for bulk and shear moduli of MP dataset
