### ISSUE TITLE
unable to run the code

### ISSUE THREAD

**Issue by PAIplus** [kdmsit/crysmmnet#3]
Hi, I try to reproduce this wonderful work. However, I can't run the code. The bugs are reported as follows:
`ModuleNotFoundError: No module named 'src_alignn'`

The python environment is setup as your instruction except the pydanic, which I changed to 1.9.1 due to the bug in 1.8.1 that "no __version attribute"

**Comment by leeyyi** [comment]
You may need to rename the profiler file. If you try to import that package but show errors.

**Comment by PAIplus** [comment]
> You may need to rename the profiler file. If you try to import that package but show errors.

well, I still can not run the code even I change the name of alignn.py to src_alignn. I do not know any other operations that are not specified in this repo should be done to run the code.

**Comment by kdmsit** [comment]
Hii Sorry for the late response.
Which file you are running and in which file (line number) you are getting this error?

**Comment by PAIplus** [comment]
I just try to run the code with the command "python train_folder.py --root_dir '../dataset/' --n_train 60000 --n_val 5000 --n_test 4132 --dataset 'MP' --property 'formation_energy'  --epochs 1000 --batch_size 64 --resume 0". The error is from the src/profile.py since it imports the src_alignn module.

**Comment by leeyyi** [comment]
> I just try to run the code with the command "python train_folder.py --root_dir '../dataset/' --n_train 60000 --n_val 5000 --n_test 4132 --dataset 'MP' --property 'formation_energy' --epochs 1000 --batch_size 64 --resume 0". The error is from the src/profile.py since it imports the src_alignn module.

I think you may need to rename the profile.py to other name.

**Comment by kdmsit** [comment]
Thanks for pointing out the issue.
rename src_alignn and src in profile.py
It should work. Let me know if there is any further issue.
We will update the repo soon.
