### ISSUE TITLE
could not find “**src_alignn**”in the project

### ISSUE THREAD

**Issue by aliezhey** [kdmsit/crysmmnet#5]
Hello, I encountered the following issue while replicating your excellent work. In the profile.py file, there is：

from src_alignn import data, models
from src_alignn.config import TrainingConfig
from src_alignn.train import group_decay, setup_optimizer

 but I could not find “**src_alignn**”in the project. How can I resolve this? Looking forward to your reply.

![Uploading QQ截图20240628104551.png…]()

**Comment by kdmsit** [comment]
Hey,
Thanks for pointing out the issue and sorry for it.
You need to rename src_alignn and src in profile.py

It should work. 
Let me know if there is any further issue.
We will update the repo soon.
